### ISSUE TITLE
Black and CI: suppress black invocation for python 3.5 and below

### ISSUE THREAD

**Issue by SebastianoF** [psf/black#1043]
Operating system: Ubuntu 18.4
Python version: *3.5*, 3.6, 3.7
*Black* version: latest
Does also happen on master: yes

It may be out of topic, as this is more a CI practice problem than a black issue.
Although, black users are more likely to have encounter this issue, and solved it, respect to the general CI practicioners.

+ There is a repository compatible (and passing tests) with python 3.5, 3.6 and 3.7.
+ Locally, black (invoked with a python 3.6 or 3.7 interpreter) formats the code flawlessly.
+ If we add the black formatting to CI (adding `pip install black` and a `black --check  .` on the CI config file), everything works flawlessly again for 3.6 and 3.7, but not for 3.5 as can not be installed on a Python interpreter version 3.5 - although it formats correctly python code down to 2+ when invoked by an interpreter 3.6+.

Is there a workaround to suppress black on version 3.5 and below, and run it only on 3.6 and 3.7 on continuous integration?

(Maybe raising a warning when trying to install black with a non compatible version instead of erroring and doing nothing when invoked, would solve the issue?) 

-----

For an example, the issue have happened to me here: https://github.com/projectmesa/mesa/pull/732. There are other repositories (also back compatible with 2.7) that would greatly benefit from black, but I am not going towards this direction because of the backward incompatibility at runtime on the CI.

Thanks for the help!!

**Comment by hugovk** [comment]
One option is to have a single build job with Python 3.6 or higher, dedicated to running Black (and possibly other lint steps).

A similar option is to only install/run Black on a supported version. For example, with Travis CI:

```yaml
language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.8-dev
    - python: 3.7
    - python: 3.6
    - python: 3.5

install:
 - pip install -U pip
 - pip install -U flake8
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install -U black; fi

script:
 # Static analysis
 - flake8 --statistics --count
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --check --diff .; fi

 # Unit tests
 ...
```
