### ISSUE TITLE
How to format modified files only

### ISSUE THREAD

**Issue by WeipingGuo** [psf/black#1278]
Hi,

I am just starting to try out black on one project. Since this is kind of legacy project, instead of formatting everything,  I am thinking to format only modified files using pre-commit hook.  Is this feasible? Any sample config is appreciated!

Thanks 
Weiping

**Comment by hugovk** [comment]
Yes, this sounds feasible. Here's some config.

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        args: ["--target-version", "py36"]
        # override until resolved: https://github.com/psf/black/issues/402
        files: \.pyi?$
        types: []
```

Adjust target version for the minimum Python you support. 

You may not need the files / types workaround.

**Comment by WeipingGuo** [comment]
Great! Thanks a lot, trying it out today.

**Comment by nicktimko** [comment]
For some projects, I tried to phase it in by ignoring all files that would fail the black check, so under `[tool.black]` I set the exclude like below. Any new files would be formatted, and if I so chose, I could unexclude files as I worked on them.

```toml
exclude = '''
(
/(
    \.git
  # other folders to ignore here...
  | dist
)/
)
# opt-in to the dark side.
  | myproject/adapters/stuff\.py
  | myproject/adapters/things\.py
  | myproject/__main__\.py
'''
```

(note that the pattern is a multi-line regex, and the first stuff needs to match with those `/`'s on the front and end.)

**Comment by ichard26** [comment]
Closing as a solution has been reached (thanks @hugovk!).

Here's an updated version of Hugo's pre-commit config with a newer version of Black and the recently added `types_or` option which fixes the bug the original config mentioned:

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: ["--target-version", "py36"]
        types_or: [python, pyi]
```
