### ISSUE TITLE
fatal: ambiguous argument 'stable': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by codeguy7k** [psf/black#1373]
[INFO] Initializing environment for https://github.com/ambv/black.
An unexpected error has occurred: CalledProcessError: Command: ('/Library/Developer/CommandLineTools/usr/libexec/git-core/git', 'reset', 'stable', '--hard')
Return code: 128
Expected return code: 0
Output: (none)
Errors: 
    fatal: ambiguous argument 'stable': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'

**Comment by scm-ns** [comment]
Same error here.

**Comment by hugovk** [comment]
The `stable` tag has been deleted, there's now only calver tags:

https://github.com/psf/black/tags

It changed in March in https://github.com/psf/black/issues/760:

> OK, this is solved. `stable` is no longer a tag, it is a **branch**.

The REAME still says advertises the `stable` tag for `.pre-commit-config.yaml`:

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6
```

And:

> Finally, `stable` is a tag that is pinned to the latest release on PyPI. If you'd rather run on master, this is also an option.

Is it possible to tell pre-commit to use the `stable` branch?
