### ISSUE TITLE
In the docs, all text in <pre> tags has a width that clips the content

### ISSUE THREAD

**Issue by SaltyCatFish** [psf/black#1506]
In the docs, any text rendered in <pre> tags has a smaller width than is permitted, which creates a scrollbar for only a few characters.

**To Reproduce** Steps to reproduce the behavior:

1. Go to https://black.readthedocs.io/en/stable/installation_and_usage.html#usage and look at the command line usage.  Full screen, there is a scroll bar at the bottom.

**Expected behavior** A clear and concise description of what you expected to happen.
1.  If I increase the width of the <pre> css to 100%, this problem goes away.

**Environment (please complete the following information):**
- OS and Python version: [e.g. Windows 10/Chrome 83.0.4103.97 (Official Build)]

**Additional context** Add any other context about the problem here.
https://imgur.com/a/PTQdOtk for an example.

**Comment by ichard26** [comment]
Hi @SaltyCatFish, thanks for noticing that and submitting a bug report. My CSS skills are pretty weak, so could you possibly explain in more detail what fixed the clipping?

**Comment by SaltyCatFish** [comment]
Sure, no problem.

It was a temp fix, I right clicked on the part that was being clipped, and
added a key:value to pre (width: 100%).

[image: image.png]

[image: image.png]

However, I think this may be an issue with Sphinx (I'm assuming thats how
you're building your docs?).

I can create a ticket and fix if that helps.

Ryan

**Comment by ichard26** [comment]
A PR would be welcomed, but again setting this in `docs/_static/custom.css` (don't mind the other css):
```css
/* Make the sidebar scrollable. Fixes https://github.com/psf/black/issues/990 */
div.sphinxsidebar {
  max-height: calc(100% - 18px);
  overflow-y: auto;
}

/* Hide scrollbar for Chrome, Safari and Opera */
div.sphinxsidebar::-webkit-scrollbar {
  display: none;
}

/* Hide scrollbar for IE 6, 7 and 8 */
@media \0screen\, screen\9 {
  div.sphinxsidebar {
    -ms-overflow-style: none;
  }
}

/* Hide scrollbar for IE 9 and 10 */
/* backslash-9 removes ie11+ & old Safari 4 */
@media screen and (min-width: 0\0) {
  div.sphinxsidebar {
    -ms-overflow-style: none\9;
  }
}

/* Hide scrollbar for IE 11 and up */
_:-ms-fullscreen,
:root div.sphinxsidebar {
  -ms-overflow-style: none;
}

/* Hide scrollbar for Edge */
@supports (-ms-ime-align: auto) {
  div.sphinxsidebar {
    -ms-overflow-style: none;
  }
}

pre {
  width: 100%;
}
```

doesn't fully mitigate the issue for me:
![Screenshot from 2020-06-16 17-28-24](https://user-images.githubusercontent.com/63936253/84830119-e8286b00-aff6-11ea-850f-35d34608af69.png)
