### ISSUE TITLE
GitHub actions error prior stable release of lint.yml

### ISSUE THREAD

**Issue by scratchmex** [psf/black#1573]
Hi, I get the following error when using GitHub Actions with black:

```
Current runner version: '2.263.0'
Operating System
Virtual Environment
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v2'
Download action repository 'actions/setup-python@v2'
Download action repository 'psf/black@stable'
##[error]Could not find file '/home/runner/work/_actions/_temp_e6a60df6-7298-4553-9c69-9049a1c24037/_staging/psf-black-6bedb5c/docs/editor_integration.md'.
```

The .yml file is the one suggested in the README as follows:

```
name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
```

_Originally posted by @Ayrx in https://github.com/psf/black/pull/1421#issuecomment-638182443_

Fixed by using `psf/black@master`.
