### ISSUE TITLE
Latest release of Black does not respect [--config .pyproject.toml] setting in pre-commit

### ISSUE THREAD

**Issue by potiuk** [psf/black#1667]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

1. Checkout latest "Apache/Airflow" sources https://github.com/apache/airflow/
2. Run `pre-commit install`
3. Run `pre-commit run black --all-files`
4. Check succeeds
5. Change black revision in .pre-commit-config.yaml to 'stable' or '20.8b1' or 'master' (currently it is '19.10b0')
6. Run `pre-commit install`
7. Run `pre-commit run black --all-files`
8. You will see a lot of files updated due to changed line length

We keep the line length in pyproject.toml and we even force the pyproject.toml file via extra arg:

```
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        files: api_connexion/.*\.py|.*providers.*\.py
        exclude: .*kubernetes_pod\.py|.*google/common/hooks/base_google\.py$
        args: [--config=./pyproject.toml]
```

Seems that the behaviour changed very recently - it was working before and people who installed pre-commit recently started to complain about it:

**Expected behavior** 

The line-lenght in pyproject.toml should be respected in black's pre-commit.

**Environment (please complete the following information):**

- Version: master, 20.8b1, stable, 20.8b0. 
- MacOS and Python version: Python 3.6.10

**Does this bug also happen on master?** 

Yes. It behaves the same with master set as revision.

**Additional context** Add any other context about the problem here.

Our pyproject.toml file:

```
[tool.black]
line-length = 110
target-version = ['py36', 'py37', 'py38']
skip-string-normalization = true
```

Also tried it with: 

```
    hooks:
      - id: black
        files: api_connexion/.*\.py|.*providers.*\.py
        exclude: .*kubernetes_pod\.py|.*google/common/hooks/base_google\.py$
        args:
          - "--config"
          - "./pyproject.toml"
```
