### ISSUE TITLE
error: cannot format /home/wojtek/workspace/portal/pustasz/apps/categories/permissions.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by wojwarych** [psf/black#1920]
**Describe the bug** A clear and concise description of what the bug is.
Formatting with black via `pre-commit` hook cannot find a way to properly format style in long and complex if/else statements

**To Reproduce** Steps to reproduce the behavior:
See `Additional context` paragraph for settings and file content which causes an error.
1. Create git repo and add error-prone file
2. Install pre-commit in venv and add black hook to .yaml config
3. Stage the file
4. `git commit -m "foo"`
5. Pre-commit fails to format this file, spits out an error

**Expected behavior** A clear and concise description of what you expected to happen.
Pre-commit fails in the first run, but it gives a formatting solution for a file. After fixing formatting pre-commit passes for black.

**Environment (please complete the following information):**
- Version: 20.8b1
- OS and Python version: Ubuntu 20.04/Python 3.7.9

**Does this bug also happen on master?**
Yes, it does. I've run file content on online formatter and it spits out same error as in title:

**Additional context** Add any other context about the problem here.
`pyproject.toml` config:
```
[tool.black]
line-length = 79
target-version = ["py37"]
exclude = "/(env|workers|migrations)/"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79
```
`pre-commit` config:
```
default_language_version:
    python: python3.7
repos:
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        language_version: python3.7
        exclude: .*\/migrations\/.*.py
```
File is added as a .txt attachement

Thanks for help in advance!
[permissions.txt](https://github.com/psf/black/files/5795905/permissions.txt)
