### ISSUE TITLE
Missing dependency typing_extensions

### ISSUE THREAD

**Issue by 0mars** [psf/black#1928]
When I run black against python 3.9.1

I get the following

```
Run pipenv run black --check .
  pipenv run black --check .
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.1/x64
Traceback (most recent call last):
  File "/home/runner/.local/share/virtualenvs/meerkat-pop4KNWc/bin/black", line 5, in <module>
    from black import patched_main
  File "/home/runner/.local/share/virtualenvs/meerkat-pop4KNWc/lib/python3.9/site-packages/black/__init__.py", line 45, in <module>
    from typing_extensions import Final
ModuleNotFoundError: No module named 'typing_extensions'
```

**To Reproduce** Steps to reproduce the behavior:

1. Take this file '...'
2. Run _Black_ on it with these arguments '....'
3. See error

**Expected behavior** A clear and concise description of what you expected to happen.

**Environment (please complete the following information):**

- Version: [e.g. master]
- OS and Python version: [e.g. Linux/Python 3.7.4rc1]

**Does this bug also happen on master?** To answer this, you have two options:

1. Use the online formatter at https://black.now.sh/?version=master, which will use the
   latest master branch.
2. Or run _Black_ on your machine:
   - create a new virtualenv (make sure it's the same Python version);
   - clone this repository;
   - run `pip install -e .`;
   - make sure it's sane by running `python -m unittest`; and
   - run `black` like you did last time.

**Additional context** Add any other context about the problem here.

**Comment by ichard26** [comment]
How did you install Black? The `typing_extensions` dependency is declared in our `setup.py` file:
https://github.com/psf/black/blob/235412635e91950c8ef2d9ebe777f97fffd4f01d/setup.py#L70-L80

**Comment by 0mars** [comment]
installed using pipenv, on github actions
```
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev

      - run: pipenv run isort --recursive --diff .
      - run: pipenv run black --check .
      - run: pipenv run flake8
      - run: pipenv run mypy
      - run: pipenv run pytest --cov --cov-fail-under=100
```
