### ISSUE TITLE
Black pre-commit hook not respecting pyproject.toml exclude config

### ISSUE THREAD

**Issue by jidicula** [psf/black#1985]
**Describe the bug**
The Black pre-commit hook blocks commits containing staged Python files not respecting Black formatting when those files are in the `tool.black` `exclude` path in `pyproject.toml`. Those files should not be causing the pre-commit hook to fail. When running `black --check .` at the repo root, the check passes, indicating the issue is specifically with the pre-commit hook.

**To Reproduce** Steps to reproduce the behavior:

1. Clone [this repo](https://github.com/jidicula/pre-commit-black) containing a minimal reproducible example of this bug.
2. Follow the directions in its README to reproduce the bug.

**Expected behavior**
Staged changes that are non-compliant with Black in files that are supposed to be ignored by Black should be able to pass the pre-commit check hook.

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: macOS 11.2.1 Python 3.7.1

**Does this bug also happen on master?** To answer this, you have two options:

Yes, see [here](https://github.com/jidicula/pre-commit-black/tree/master-black). However, I could only use the commit at the HEAD of `master` on the day I tried this out (today, 2021-02-13), since pre-commit does not allow branchnames for the value of `rev`.

**Additional context** Add any other context about the problem here.
None

**Comment by ichard26** [comment]
See https://github.com/psf/black/issues/438. The problem is that pre-commit passes the files it wants the Black hook to check directly via the CLI instead of letting Black find them by itself. Files directly passed through the CLI aren't subject to the `---include/--exclude` regexes since they only apply to **recursively found files and directories**. Try using `--force-exclude` which behaves like `--exclude` but also applies to files and directories directly given through the CLI.

**Comment by jidicula** [comment]
Thanks @ichard26! I'm still struggling to get this set up though. How should I be passing the path to the `--force-exclude` option? This is what I currently have and it's still failing the pre-commit hook when I change any Python file in the `ignored/` path.

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: b8c1020b526b488a1a216d9a4d58fc8616b61a99
    hooks:
      - id: black
        language_version: python3
        args:
          - --force-exclude='ignored/'
```

**Comment by ichard26** [comment]
```yaml
repos:
  - repo: https://github.com/psf/black
    rev: b8c1020b526b488a1a216d9a4d58fc8616b61a99
    hooks:
      - id: black
        language_version: python3
        args: [--force-exclude, ignored/]
```
maybe??? (I don't use pre-commit or YAML syntax to be 100% sure)

You could also just use the `--force-exclude` option via your `pyproject.toml` config file.
