### ISSUE TITLE
Current master fails in python 3.7 (see commit id in ticket)

### ISSUE THREAD

**Issue by IanTP-Blink** [psf/black#2201]
Commit to master https://github.com/psf/black/commit/5316836393682c6ec6a05d69c549d8167f46d8f6 causes full failure of github actions with message `/entrypoint.sh: line 9: syntax error: unexpected end of file`.

**To Reproduce** Steps to reproduce the behavior:

1. Set up a github action with a python 3.7.5 project
2. Use black with this commit present https://github.com/psf/black/commit/5316836393682c6ec6a05d69c549d8167f46d8f6 (currently active as "master" as of this ticket)
3. Use roughly:
```
   lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@master
```
4. See error `/entrypoint.sh: line 9: syntax error: unexpected end of file`

**Expected behavior** Lint should not fail with a syntax error. version `uses: psf/black@stable` still works fine.

**Environment (please complete the following information):**

- Version: master
- OS and Python version: ubuntu-latest per github, python 3.7.5

**Does this bug also happen on master?** **Yes.**
