### ISSUE TITLE
Add options to toml config file

### ISSUE THREAD

**Issue by gonzaloamadio** [psf/black#2220]
Hi, 

How can I add options to toml config file:

Basically I would like to execute black with the -S flag always.

How can I achieve this?

**Comment by ichard26** [comment]
Use a `pyproject.toml` file with Black's config under the `tool.black` table:

```toml
[tool.black]
skip-string-normalization = true
```
