### ISSUE TITLE
Docker release - tags used for created images

### ISSUE THREAD

**Issue by pszlazak** [psf/black#2373]
**Describe the bug**

When you are creating Docker image, you always tag it with `latest` tag and either:
- Git tag
or:
- `latest_non_release`

This is done in line # 41 of [docker.yml](https://github.com/psf/black/blob/main/.github/workflows/docker.yml#L41).
Earlier `GIT_TAG` is prepared in line # 32 of [docker.yml](https://github.com/psf/black/blob/main/.github/workflows/docker.yml#L32).

**To Reproduce**

Pull both images:
```
$ docker pull pyfound/black:latest
$ docker pull pyfound/black:latest_non_release
```

Check version of Black for both images:
```
$ docker run --rm -it pyfound/black:latest black --version
black, version 0.1.dev1+g91773b8
$ docker run --rm -it pyfound/black:latest_non_release black --version
black, version 0.1.dev1+g91773b8
```

Of course, there can be a point in time when `latest` is same as image tagged with Git tag, but every push to `main` branch will produce new Docker image.

**Expected behavior**

`latest` tag should correspond to latest released version of Black. So in my automation I can always pull Docker image related to the newest released version of Black.

**Environment (please complete the following information):**

N/A

**Does this bug also happen on main?**

N/A

**Additional context**

N/A

**Comment by cooperlees** [comment]
Hi,

Thanks for the report, but that is not how docker hub works by default and how most projects seem to use default latest tagging with their docker images too. We don’t control the `latest` tag, it gets auto moved with every upload. Most other docker projects (from what I seen) use latest for every version that gets upload too. I’d prefer we stay the norm for docker (happy to be proven wrong here).

So our tagging today is:
- Version only
- Everything else gets latest_non_release
- Everything gets latest at time of upload

I guess we could introduce a tag (maybe `latest_release`) to achieve what you want here. If we could update the action to move this tag on a release I’d happily accept that. I might get to trying to add this one day, but I don’t know how to achieve this off the top of my head in the action `.yaml` config …

**Comment by pszlazak** [comment]
Just confirmed using open source [Docker Registry](https://docs.docker.com/registry/):
- if you push without tag, `latest` tag will be added automatically
- but if you push with any tag, no `latest` is created

So I can be in the situation where I have:
- image with tag `v1` and `latest`
- image with tag `v2` (of course with some changes)

Then I can retag them, so `latest` is used for `v2`.

I guess the problem is with following line of [`docker.yml`](https://github.com/psf/black/blob/main/.github/workflows/docker.yml):
```
tags: pyfound/black:latest,pyfound/black:${{ env.GIT_TAG }}
      ^^^^^^^^^^^^^^^^^^^^
```
Maybe you should have two separate steps:
```
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: pyfound/black:${{ env.GIT_TAG }}
      - name: Build and push latest tag
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: pyfound/black:latest
```
Please check following documentation:
- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-contexts
- https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release

Although I have no place to check if it works.
