### ISSUE TITLE
black-jupyter aborted under pre-commit

### ISSUE THREAD

**Issue by 12rambau** [psf/black#2446]
**Describe the bug**

I cannot use `black-jupyter` in my precommit list

**To Reproduce**

I have the following .pre-commit-config.yaml : 

```yaml
default_language_version:
    python: python3

repos:
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black
    -   id: black-jupyter
```

the precommit hook fails with the following error message : 
> [ERROR] `black-jupyter` is not present in repository https://github.com/psf/black.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.

If I run `pre-commit autoupdate`as suggested in the error message I also get an error message:
> Updating https://github.com/psf/black ... Cannot update because the update target is missing these hooks:
black-jupyter

I followed the following page instruction to create my hooks: https://pre-commit.com/hooks.html, maybe the list is outdated
