### ISSUE TITLE
Using version specifier in GitHub Action fails

### ISSUE THREAD

**Issue by lofidevops** [psf/black#3316]
**Describe the bug**

Using version specifier in GitHub Action fails. I believe this is because the stable branch has not been updated.

**To Reproduce**

Add the following GitHub Action to your repo:

```
name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose --skip-magic-trailing-comma"
          version: "~= 22.0"
```

The resulting error is:

```
ERROR: Invalid requirement: 'black[colorama]==~= 22.0'

Error: Failed to install Black.
Error: Process completed with exit code 1.
```

See https://github.com/canonical-ols/acceptable/actions/runs/3206267998/jobs/5239812322 for an example. (I'm not sure if the logs are visible to everyone?)

**Expected behavior**

Black 22.x should install as expected. Linter should run.

**Environment**

GitHub Action. See action file above.

**Additional notes**

I noticed that although 22.10.0 has been released, https://github.com/psf/black/tree/stable has not been updated.
