### ISSUE TITLE
Documenting black-jupyter pre-commit hook

### ISSUE THREAD

**Issue by jamesbraza** [psf/black#3641]
**Is this related to a problem? Please describe.**

The [Version control integration](https://black.readthedocs.io/en/stable/integrations/source_version_control.html#version-control-integration) briefly mentions `black-jupyter`:

> The `black-jupyter` hook is only available from version 21.8b0 and onwards.

Also, searching the docs for it, barely anything comes up.  To figure out how to use, I came upon this: https://github.com/psf/black/blob/23.3.0/.pre-commit-hooks.yaml

And some results ([here](https://github.com/shanku007/pro-orch/blob/master/.pre-commit-config.yaml), [here](https://github.com/rocs-org/datascience-template/blob/main/.pre-commit-config.yaml)) from a GitHub advanced search.

**Describe the solution you'd like**

It would be useful for `black` to document this integration officially, and maybe address a few questions:
- Why does `black-jupyter` require `additional_dependencies: [".[jupyter]"]`?
    - Shouldn't `black-jupyter` self-install `jupyter`?
- Should it include `types_or: [python, pyi, jupyter]`, `entry`?
- Why is `require_serial: true` not in the suggested the previously documented Black config?

```yaml
---
default_language_version:
  python: python3

repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black  # Does one still need black here?
      - id: black-jupyter
        entry: black
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi, jupyter]
        additional_dependencies: [".[jupyter]"]
```

**Describe alternatives you've considered**

N/a

**Additional context**

N/a

**Comment by MarcoGorelli** [comment]
Hey @jamesbraza 

> Why does black-jupyter require additional_dependencies: [".[jupyter]"]? Shouldn't black-jupyter self-install jupyter?

You're right, it does - you don't need to manually specify `additional_dependencies`

> Should it include types_or: [python, pyi, jupyter], entry?

The hook already contains this, you don't need to specify it

> Why is require_serial: true not in the suggested the previously documented Black config?

It's already in the hook, you don't need to specify it yourself:

https://github.com/psf/black/blob/a552f7096a9f6e016c9bb1df1e0a77a17caeec1c/.pre-commit-hooks.yaml#L16

>       - id: black  # Does one still need black here?

Nope - if you have `black-jupyter`, that's all you need. It'll run on Python files, pyi files, and also on Jupyter ones

**Comment by jamesbraza** [comment]
Ah I see, I realize now that [`.pre-commit-hooks.yaml`](https://github.com/psf/black/blob/23.3.0/.pre-commit-hooks.yaml) is sort of the "server" in the `pre-commit` relationship.

So the correct `.pre-commit-config` for `black-jupyter` would be:

```yaml
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black-jupyter
        description: Black, with Jupyter Notebook support
```

And if that's correct, would you be interested in me making a PR to add something like that to the docs?
