### ISSUE TITLE
(🎁) Ability to specify default files in the config

### ISSUE THREAD

**Issue by KotlinIsland** [psf/black#3646]
I want to be able to specify the default files within the configuration file so that I don't need to duplicate this config in different places.

```toml
[tool.black]
files = ["src", "scripts"]
```

Then it is possible to invoke black without passing any paths:
```
👉 black
yada yada yada ✨
```

Related: https://github.com/charliermarsh/ruff/issues/3970
