### ISSUE TITLE
GitHub Action fails

### ISSUE THREAD

**Issue by huhlim** [psf/black#3953]
**Describe the bug**
GitHub Action fails with the latest version, 23.10.0. If I specify a version (e.g., 23.9.0), it works fine.
I have been using the GitHub Action snippet as described on [this page](https://black.readthedocs.io/en/stable/integrations/github_actions.html). 

**To Reproduce**

For example, take this code:

```
name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
```

The resulting error is:
The GitHub Action raises an error. 
![스크린샷 2023-10-17 오후 5 40 45](https://github.com/psf/black/assets/13167164/f9a7b6dd-1733-455f-8b0e-29392f267016)

**Expected behavior**
If I specify a _black_ version like this, it works fine.
```
name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@23.9.1
        with:
          options: "--check --verbose"
```

**Environment**

- Black's version: psf/black@stable (or 23.10.0)
- OS and Python version: GitHub Action

**Additional context**
