### ISSUE TITLE
pre-commit hook does not work for .pyi files

### ISSUE THREAD

**Issue by chadrik** [psf/black#402]
Because of this issue https://github.com/chriskuehl/identify/issues/51

For now I can solve this by overriding `files` and `types` in `.pre-commit-config.yaml`:

```yaml
repos:
  - repo: https://github.com/ambv/black
    rev: 18.6b4
    hooks:
      - id: black
        language_version: python3.6
        files: \.pyi?$
        types: []
```

I would recommend that `black` use `files` instead of `types` until this issue is resolved in `identify` and `pre-commit`.

Operating system: osx
Python version: 3.6
*Black* version: 18.6b4
Does also happen on master: yep
