### ISSUE TITLE
[ISSUE] Github Action Black failing after successful reformatting.

### ISSUE THREAD

**Issue by tikendraw** [psf/black#4156]
**Describe the bug**

Trying to use Black in github actions and  it is failing after reformatting. 
Shouldn't it  be passing after reformatting without errors ?
```
name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
```

**To Reproduce**
use black in github action

**The resulting error is:**
failing github action after reformatting
```
would reformat /home/runner/work/catsay/catsay/catsay/cat.py

Oh no! 💥 💔 💥
1 file would be reformatted, 4 files would be left unchanged.
Error: Process completed with exit code 1.
```

**Expected behavior**
If black has reformatted files witout any errors then actions should pass a success, not a fail
