### ISSUE TITLE
precommit black doesn't read from `pyproject.toml` file. 

### ISSUE THREAD

**Issue by arshan-ritual** [psf/black#4317]
**Describe the bug**

My precommit file: 
```
repos:
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.289
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

etc.
```
My `pyproject.toml` file:
```
[tool.black]
line-length = 89

[tool.isort]
profile = "black"
skip = [".gitignore", ".dockerignore"]
```

I'm running this. Black sets line length to 120 by default & doesn't read from my config.
```
pre-commit run --all-files
black....................................................................Passed
ruff.....................................................................Failed
- hook id: ruff
- exit code: 1

src/chain/errors.py:56:90: E501 Line too long (103 > 89 characters)
src/chain/errors.py:57:90: E501 Line too long (103 > 89 characters)
src/chain/errors.py:58:90: E501 Line too long (107 > 89 characters)
src/chain/errors.py:59:90: E501 Line too long (112 > 89 characters)
src/chain/errors.py:61:90: E501 Line too long (96 > 89 characters)
src/chain/errors.py:63:90: E501 Line too long (99 > 89 characters)
src/chain/errors.py:64:90: E501 Line too long (115 > 89 characters)
Found 7 errors.

mypy.....................................................................Passed
isort (python)...........................................................Passed
Fix End of Files.........................................................Passed
Check for added large files..............................................Passed
Trim Trailing Whitespace.................................................Passed
```
