### ISSUE TITLE
No configuration used for paths after the first

### ISSUE THREAD

**Issue by tmct** [psf/black#4461]
### Describe the bug

Black configurations are seemingly not taken into account for any paths after the first one passed to CLI - I'm seeing this in particular for "line-length" but have no reason to expect the behaviour is specifically related to that option.

Specifically this prevents me from running black on multiple projects in one command. Perhaps this is by design.

#### Black version
```
black, 24.8.0 (compiled: yes)
Python (CPython) 3.10.10
```

#### Project setup

```python
# repro/proj1/hi.py
print("hi")
```

```toml
# repro/proj1/pyproject.toml
[project]
name = "proj1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.black]
line-length = 120
```

```python
# repro/proj2/hello.py
import os


def main():
    return "abcdefghijk" if os.getcwd() is not None else "aeheahaehaeh;kaehbnmieasolngoaeinaeghaehgoiaen"


if __name__ == "__main__":
    main()
```
```toml
# repro/proj2/pyproject.toml
[project]
name = "proj2"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[tool.black]
line-length = 120
```

#### Actual behaviour

(running commands from inside proj1)
```bash
$ black --check --diff . 
All done! ✨ 🍰 ✨
1 file would be left unchanged.
```
```
$ black --check --diff ../proj2
All done! ✨ 🍰 ✨
1 file would be left unchanged.
```
```
$ black --check --diff . ../proj2
--- /home/tom/code/repro/proj2/hello.py  2024-09-18 13:23:06.381794+00:00
+++ /home/tom/code/repro/proj2/hello.py  2024-09-18 13:44:24.114345+00:00
@@ -1,9 +1,13 @@
 import os
 
 
 def main():
-    return "abcdefghijk" if os.getcwd() is not None else "aeheahaehaeh;kaehbnmieasolngoaeinaeghaehgoiaen"
+    return (
+        "abcdefghijk"
+        if os.getcwd() is not None
+        else "aeheahaehaeh;kaehbnmieasolngoaeinaeghaehgoiaen"
+    )
 
 
 if __name__ == "__main__":
     main()
would reformat /home/tom/code/repro/proj2/hello.py

Oh no! 💥 💔 💥
1 file would be reformatted, 1 file would be left unchanged.
```

#### Expected behavior

Either one of the configurations would be taken into account, and I would be able to check both folders at once. (I don't mind which in my use case - these particular projects have identical tooling configurations.)

### Environment

- Black's version: 24.8.0
- OS and Python version: [Ubuntu 20.04/Python (CPython) 3.10.10]

Thanks
