### ISSUE TITLE
Black support for Databricks notebook formatting - Ignore lines starting with ! or %

### ISSUE THREAD

**Issue by vivek-freddy** [psf/black#4556]
I have a .py file which runs as notebook 
```
# Databricks notebook source
!pip install -U dspy python-dotenv
!pip install torchmetrics
dbutils.library.restartPython() 
# COMMAND ----------
from tqdm.notebook import tqdm
tqdm.pandas()
import logging
# COMMAND ----------
!pip install matplotlib seaborn
```

The above is python file which runs as notebook where each cell is defined by # COMMAND in databricks. When applying black formatting I want to skip the pip install related lines. I tried using noqa but still above is causing warnings. How do I skip checking lines which have ! or % as starting character?

My pre-commit file config is 

```
repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [ python, pyi ]
      - id: black-jupyter
        name: black-jupyter
        description:
          "Black: The uncompromising Python code formatter (with Jupyter Notebook support)"
        entry: black
        language: python
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [ python, pyi, jupyter ]
        additional_dependencies: [ ".[jupyter]" ]
```
On running 
```
pre-commit run --all-files
```

Warnings which I get is

```
Cannot parse: 7:0: !pip install -U dspy python-dotenv
```
