### ISSUE TITLE
Excluding directory in django project with pre-commit not working

### ISSUE THREAD

**Issue by anuj-scanova** [psf/black#4595]
**Describe the bug**

Using `pre-commit` in Django and want to exclude the `migrations` directory and all files of it from formatting because these are auto-generated files by Django. Tried with `exclude`, `extend-exclude`, and `force-exclude` but none of them seems to be working as expected
**To Reproduce**
```yml
repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0  # Use the latest stable version
    hooks:
      - id: black
        language_version: python3
        exclude: |
          (?x)(
              ^migrations/
          )
```

Also tried `pyproject.toml`
```toml
[tool.black]
line-length = 88
skip-string-normalization = true
extend-exclude = '''
/(
  | migrations
)/
'''
```

And run it with these arguments:

```sh
$ pre-commit run --all-files
```

The resulting error is:

> There is no error but the migrations are also being formatted
> reformatted src/utils/migrations/0002_cancelsubscriptionfeedback.py
reformatted src/utils/migrations/0006_alter_netpromoterscore_user.py
reformatted src/utils/migrations/0003_auto_20230706_1152.py
reformatted src/utils/migrations/0007_feedback_reminder.py
reformatted src/user_media/migrations/0005_auto_20240925_0107.py
reformatted src/utils/migrations/0004_netpromoterscore.py
reformatted src/payments/migrations/0001_initial.py
reformatted src/webhook_integration/migrations/0004_auto_20220422_1201.py
reformatted src/user_logs_export/migrations/0004_auto_20250123_1931.py
reformatted src/webhook_integration/migrations/0005_auto_20230403_1147.py
reformatted src/webhook_integration/migrations/0006_auto_20230418_0542.py
reformatted src/webhook_integration/migrations/0002_eventtrackingwebhook.py
reformatted src/webhook_integration/migrations/0003_eventtrackinggoogleanalytics.py
reformatted src/webhook_integration/migrations/0001_initial.py
reformatted src/tracking/migrations/0001_initial.py

**Expected behavior**

`migrations` should not be formatted
**Environment**

- Black's version: 25.1.0
- OS and Python version: Mac OS

**Additional context**
