### ISSUE TITLE
black hook unexpectedly removes exception alias during pre-commi

### ISSUE THREAD

**Issue by bfbarry** [psf/black#4683]
**Describe the bug**

After running `pre-commit`, the `black` hook removed an exception alias - it must've though it was redundant given a prior still-in-scope iterable of the same name `e`. Regardless that renaming `e` is a fix, this is still incorrect behavior, since the except block is of course referring to the alias.

```python
for e in emails:
    pass

...
-    except Exception as e:
+    except Exception:
         logger.error(f"err: {str(e)}")
```

**To Reproduce**

test.py:
```python
for e in emails:
    pass
try:
    raise Exception("test")
except Exception as e:
         logger.error(f"err: {str(e)}")
```

pre-commit version 3.2.2
- black, 25.1.0 (compiled: yes)
Python (CPython) 3.11.0
- MacOs, python 3.11, 

And run it with these arguments:

```sh
$ pre-commit run --all-files
```

The resulting error is removing the `as e` alias:

**Expected behavior**

Not remove the alias

**Environment**

.pre-commit-config.yaml:
```yaml
repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    - id: black
      language_version: python3.11

  # this is a fork which keeps compatibility with black
  - repo: https://github.com/wimglenn/reorder-python-imports-black
    rev: v3.14.0
    hooks:
    - id: reorder-python-imports
      args: ['--py311-plus', '--application-directories=backend/']
      # need to ignore alembic files, since reorder-python-imports gets confused
      # and thinks that alembic is a local package since there is a folder
      # in the backend directory called `alembic`
      exclude: ^backend/alembic/

  # These settings will remove unused imports with side effects
  # Note: The repo currently does not and should not have imports with side effects
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [ '--remove-all-unused-imports', '--remove-unused-variables', '--in-place' , '--recursive']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.4
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    - id: prettier
      types_or: [html, css, javascript, ts, tsx]
      additional_dependencies:
      - prettier
```
